version: '2'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
          - ./docker/postgresql/schema.sql:/docker-entrypoint-initdb.d/z01_schema.sql
    environment:
      POSTGRES_PASSWORD: ship
      POSTGRES_USER: ship